"""Fix language_code

Revision ID: c0682b0434ea
Revises: 2f7eb908855b
Create Date: 2024-12-16 20:34:20.169621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0682b0434ea"
down_revision: Union[str, None] = "2f7eb908855b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "language_code",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "language_code",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
