"""Create table

Revision ID: 944406dd5f54
Revises: 
Create Date: 2024-03-14 11:17:40.755182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "944406dd5f54"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_chat",
        sa.Column("id_chat", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("group_name", sa.String(length=20), nullable=True),
        sa.Column("activity", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("schedule_time", sa.String(length=5), nullable=True),
        sa.PrimaryKeyConstraint("id_chat"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_chat")
    # ### end Alembic commands ###
