"""Update language_code and referrer_id

Revision ID: 54662db40d38
Revises: a05c2bf17175
Create Date: 2025-01-26 21:26:30.943635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54662db40d38"
down_revision: Union[str, None] = "a05c2bf17175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "language_code",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "user",
        "referrer_id",
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "referrer_id",
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "language_code",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
